import { useState, useCallback } from "react";
import { ArrowLeft, FileSpreadsheet, Download, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useDropzone } from "react-dropzone";
import ProcessingState from "./ProcessingState";
import { celebrateSuccess } from "@/lib/confetti";
import { toast } from "@/hooks/use-toast";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ExcelToPDFWorkspaceProps {
  onBack: () => void;
}

interface ExcelData {
  headers: string[];
  rows: string[][];
  fileName: string;
}

const ExcelToPDFWorkspace = ({ onBack }: ExcelToPDFWorkspaceProps) => {
  const [excelData, setExcelData] = useState<ExcelData | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [progress, setProgress] = useState(0);

  const parseExcel = useCallback((file: File): Promise<ExcelData> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const data = new Uint8Array(e.target?.result as ArrayBuffer);
          const workbook = XLSX.read(data, { type: "array" });
          const firstSheetName = workbook.SheetNames[0];
          const worksheet = workbook.Sheets[firstSheetName];
          const jsonData = XLSX.utils.sheet_to_json<string[]>(worksheet, { header: 1 });
          
          if (jsonData.length === 0) {
            reject(new Error("Empty spreadsheet"));
            return;
          }

          const headers = (jsonData[0] as string[]).map(h => String(h || ""));
          const rows = jsonData.slice(1).map(row => 
            (row as string[]).map(cell => String(cell || ""))
          );

          resolve({
            headers,
            rows,
            fileName: file.name.replace(/\.(xlsx|xls)$/i, "")
          });
        } catch (error) {
          reject(error);
        }
      };
      reader.onerror = () => reject(new Error("Failed to read file"));
      reader.readAsArrayBuffer(file);
    });
  }, []);

  const onDrop = useCallback(async (acceptedFiles: File[]) => {
    if (acceptedFiles.length === 0) return;
    
    try {
      const data = await parseExcel(acceptedFiles[0]);
      setExcelData(data);
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to parse Excel file. Please try again.",
        variant: "destructive"
      });
    }
  }, [parseExcel]);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: {
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [".xlsx"],
      "application/vnd.ms-excel": [".xls"]
    },
    multiple: false
  });

  const handleConvert = async () => {
    if (!excelData) return;

    setIsProcessing(true);
    setProgress(0);

    try {
      // Simulate progress
      const progressInterval = setInterval(() => {
        setProgress(prev => Math.min(prev + 15, 90));
      }, 200);

      const doc = new jsPDF();
      
      // Add title with Digital India styling
      doc.setFontSize(18);
      doc.setTextColor(255, 128, 0); // Saffron color
      doc.text(excelData.fileName, 14, 20);
      
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated by PDF Love India`, 14, 28);

      // Create table with Digital India styling
      autoTable(doc, {
        head: [excelData.headers],
        body: excelData.rows,
        startY: 35,
        theme: "grid",
        headStyles: {
          fillColor: [255, 128, 0], // Saffron header
          textColor: [255, 255, 255],
          fontStyle: "bold",
          halign: "center"
        },
        alternateRowStyles: {
          fillColor: [248, 250, 252] // Light gray
        },
        styles: {
          cellPadding: 4,
          fontSize: 9,
          valign: "middle"
        },
        columnStyles: {
          0: { fontStyle: "bold" }
        }
      });

      clearInterval(progressInterval);
      setProgress(100);

      // Download PDF
      doc.save(`${excelData.fileName}.pdf`);

      await new Promise(resolve => setTimeout(resolve, 500));
      
      celebrateSuccess();
      toast({
        title: "Success!",
        description: "Your Excel file has been converted to PDF."
      });

      setIsProcessing(false);
      setProgress(0);
    } catch (error) {
      setIsProcessing(false);
      toast({
        title: "Error",
        description: "Failed to convert Excel to PDF.",
        variant: "destructive"
      });
    }
  };

  const handleClear = () => {
    setExcelData(null);
  };

  if (isProcessing) {
    return (
      <ProcessingState
        status="processing"
        message="Converting to PDF..."
        progress={progress}
      />
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b border-border bg-card">
        <div className="container py-4">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" onClick={onBack} className="shrink-0">
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <div>
              <h1 className="text-xl font-bold text-foreground">Excel to PDF</h1>
              <p className="text-sm text-muted-foreground">
                Convert spreadsheets into beautiful PDF tables
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="container py-8">
        {!excelData ? (
          <div
            {...getRootProps()}
            className={`mx-auto max-w-xl cursor-pointer rounded-2xl border-2 border-dashed p-12 text-center transition-all ${
              isDragActive
                ? "border-india-green bg-india-green/5"
                : "border-border hover:border-india-green/50 hover:bg-muted/50"
            }`}
          >
            <input {...getInputProps()} />
            <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-india-green/10">
              <Upload className="h-8 w-8 text-india-green" />
            </div>
            <p className="mb-2 text-lg font-medium text-foreground">
              {isDragActive ? "Drop your Excel file here" : "Upload Excel File"}
            </p>
            <p className="text-sm text-muted-foreground">
              Supports .xlsx and .xls files
            </p>
          </div>
        ) : (
          <div className="mx-auto max-w-4xl">
            {/* File Info */}
            <div className="mb-6 flex items-center justify-between rounded-xl border border-border bg-card p-4">
              <div className="flex items-center gap-3">
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-india-green/10">
                  <FileSpreadsheet className="h-6 w-6 text-india-green" />
                </div>
                <div>
                  <p className="font-medium text-foreground">{excelData.fileName}</p>
                  <p className="text-sm text-muted-foreground">
                    {excelData.headers.length} columns, {excelData.rows.length} rows
                  </p>
                </div>
              </div>
              <Button variant="outline" size="sm" onClick={handleClear}>
                Remove
              </Button>
            </div>

            {/* Preview Table */}
            <div className="mb-6 overflow-hidden rounded-xl border border-border">
              <div className="bg-muted/50 px-4 py-3 border-b border-border">
                <p className="text-sm font-medium text-foreground">Preview (first 5 rows)</p>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="bg-india-saffron text-white">
                      {excelData.headers.map((header, i) => (
                        <th key={i} className="px-4 py-3 text-left text-sm font-semibold">
                          {header || `Column ${i + 1}`}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {excelData.rows.slice(0, 5).map((row, rowIndex) => (
                      <tr key={rowIndex} className={rowIndex % 2 === 0 ? "bg-background" : "bg-muted/30"}>
                        {excelData.headers.map((_, colIndex) => (
                          <td key={colIndex} className="px-4 py-2 text-sm text-foreground">
                            {row[colIndex] || ""}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              {excelData.rows.length > 5 && (
                <div className="bg-muted/30 px-4 py-2 text-center text-sm text-muted-foreground border-t border-border">
                  ... and {excelData.rows.length - 5} more rows
                </div>
              )}
            </div>

            {/* Convert Button */}
            <div className="flex justify-center">
              <Button variant="india" size="lg" onClick={handleConvert} className="gap-2">
                <Download className="h-5 w-5" />
                Convert to PDF
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ExcelToPDFWorkspace;
